### ISSUE TITLE
Whats is the user name and password for demo app published in apple store?

### ISSUE THREAD

**Issue by loki4u** [Beaconstac/iOS-SDK#3]
HI Team,

Whats is the user name and password for demo app published in apple store?

**Comment by firecast** [comment]
The demo app is only for Beaconstac customers.
To start using the app, you need to buy Beaconstac beacons with a subscription plan. Here is the [link](https://store.beaconstac.com/) to do the same. Once your order is shipped, you'll receive an email with the login details.
