### ISSUE TITLE
Need detail info

### ISSUE THREAD

**Issue by loki4u** [Beaconstac/iOS-SDK#4]
[beaconstacInstance startRangingBeaconsWithUUIDString:@**"F94DBB23-2266-7822-3782-57BEAC0952AC**" beaconIdentifier:@"MobstacRegion" filterOptions:nil];

Here whats is this?
**startRangingBeaconsWithUUIDString**

**Comment by firecast** [comment]
Ranging for beacons require a beacon UUID string to be passed in. All of Beaconstac beacons have the same UUID (F94DBB23-2266-7822-3782-57BEAC0952AC) and the function startRangingBeaconsWithUUIDString starts ranging for beacons for the provided UUID string. For more information please refer to our documentation [site](http://docs.beaconstac.com/).
