### ISSUE TITLE
Application crashing

### ISSUE THREAD

**Issue by prahaladfulle** [Beaconstac/iOS-SDK#7]
dyld: Symbol not found: __T016EddystoneScanner0B0CN
  Referenced from: /private/var/containers/Bundle/Application/1EA37DD9-7F6B-4911-8912-109D85E6AA08/BeaconstacDemo.app/Frameworks/Beaconstac.framework/Beaconstac

**Comment by sachinmobstac** [comment]
If you are using the Pods, make sure you add the EddystoneScanner as well.

**Comment by prahaladfulle** [comment]
Hello Sachinmobstac 

Thanks for your response.

> If you are using the Pods, make sure you add the EddystoneScanner as well.
yes I have using pods. and EddystoneScanner.
