### ISSUE TITLE
Can we get this updated to Swift 5.2?

### ISSUE THREAD

**Issue by ehlersd** [Beaconstac/iOS-SDK#9]
The specific error I'm receiving with Xcode 11.2.1 is:

`Module compiled with Swift 5.0 cannot be imported by the Swift 5.1.2 compiler: /Users/darrenehlers/Google Drive/development/DNSFramework/TestApp/Pods/Beaconstac/Beaconstac/Beaconstac.framework/Modules/Beaconstac.swiftmodule/arm64.swiftmodule`

**Comment by ravipratapm** [comment]
We don't support Swift 5.2 yet, sorry about that. Please use Swift 5.0

**Comment by ehlersd** [comment]
But that's not the problem.  The problem is that even using Swift 5.0, it will not link with the later versions of Xcode.  Look specifically at the error message I shared above:

"Module compiled with Swift 5.0 cannot be imported by the Swift 5.1.2 compiler"

This is not referring to the version of Swift, but the version of the Compiler.  The framework needs to be rebuild with the later versions of Xcode (ie: 11.2.1) and a new Cocoapod release put out.  It shouldn't really require any code changes.

**Comment by ravipratapm** [comment]
Can you switch to XCode 10.x? We haven't upgraded to XCode 11.x yet.

**Comment by ehlersd** [comment]
Unfortunately, due to the libraries we are using, that is not an option.  We are required to use Xcode 11.x.  I'll have to discuss it with our sales rep.

**Comment by ravipratapm** [comment]
We are working on it at the moment. ETA is Dec 15.

**Comment by ehlersd** [comment]
OH! In that case, we are good.  Let me know if I can help test in any way...

**Comment by ehlersd** [comment]
@ravipratapm How are you doing on the library update?  Thx!

**Comment by ravipratapm** [comment]
@ehlersd We're currently working on it, but a little behind at the moment. Give us until after the Christmas break to get it out and released.

**Comment by ehlersd** [comment]
Thanks for the update and have a Merry Christmas!

**Comment by Souro7** [comment]
@ehlersd We have released v3.2.6 with Xcode 11.x support.

**Comment by Souro7** [comment]
Closing this issue as new version with Xcode 11 support has been released.
